apiVersion: v1
kind: Service
metadata:
  name: service-claster-ip-python-server
spec:
  type: ClusterIP # default type is ClusterIP
  selector:
    app: python-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80